import outlookIcon from "./assets/outlook_icon.png";
import calendarIcon from "./assets/calendar_icon.png";
import serviceNowIcon from "./assets/service_now.png";
import concurIcon from "./assets/concur_icon.png";
import gitIcon from "./assets/git_icon.png";
import jiraIcon from "./assets/jira_icon.png";
import fbworkIcon from "./assets/fbwork_icon.png";
import slackIcon from "./assets/slackIcon.png";
import teamsIcon from "./assets/teams_icon.png";

export const settingsData = [
  {
    itemId: "5001",
    itemName: "Meetings",
    itemImage: calendarIcon,
    itemRating: 4,
    itemAdded: true,
    itemStyle: {
      height: 27,
      width: 27,
      position: "relative",
      top: 10,
    },
  },
  {
    itemId: "5002",
    itemName: "Outlook",
    itemImage: outlookIcon,
    itemRating: 4,
    itemAdded: true,
    itemStyle: {
      height: 32,
      width: 32,
      position: "relative",
      top: 7,
    },
  },
  {
    itemId: "5009",
    itemName: "Teams",
    itemImage: teamsIcon,
    itemRating: 4,
    itemAdded: false,
    itemStyle: {
      height: 20,
      width: 22,
      position: "relative",
      top: 12,
    },
  },
  {
    itemId: "5008",
    itemName: "Slack",
    itemImage: slackIcon,
    itemRating: 5,
    itemAdded: false,
    itemStyle: {
      height: 22,
      width: 22,
      position: "relative",
      top: 11,
    },
  },
  {
    itemId: "5007",
    itemName: "Fb @ Work",
    itemImage: fbworkIcon,
    itemRating: 3,
    itemAdded: false,
    itemStyle: {
      height: 22,
      width: 22,
      position: "relative",
      top: 11,
    },
  },
  {
    itemId: "5003",
    itemName: "Service Now",
    itemImage: serviceNowIcon,
    itemRating: 3,
    itemAdded: true,
    itemStyle: {
      height: 22,
      width: 22,
      position: "relative",
      top: 11,
    },
  },
  {
    itemId: "5004",
    itemName: "Concur",
    itemImage: concurIcon,
    itemRating: 3,
    itemAdded: true,
    itemStyle: {
      height: 22,
      width: 22,
      position: "relative",
      top: 11,
    },
  },
  {
    itemId: "5005",
    itemName: "Git",
    itemImage: gitIcon,
    itemRating: 4,
    itemAdded: true,
    itemStyle: {
      height: 22,
      width: 22,
      position: "relative",
      top: 11,
    },
  },
  {
    itemId: "5006",
    itemName: "Jira",
    itemImage: jiraIcon,
    itemRating: 4,
    itemAdded: true,
    itemStyle: {
      height: 22,
      width: 22,
      position: "relative",
      top: 11,
    },
  },
];

export const categoryCardDetails = [
  {
    cardId: "1001",
    cardTitle: "Meetings",
    cardMatch: "Meetings",
    cardTaskTitle: "6 Requests",
    //cardColor: "rgba(255, 192, 56, 1)",
    cardColor: "#fff",
  },
  {
    cardId: "1002",
    cardTitle: "Mails",
    cardMatch: "Mail",
    cardTaskTitle: "1 Unread",
    //cardColor: "rgba(11, 165, 254, 1)",
    cardColor: "#fff",
  },
  {
    cardId: "1003",
    cardTitle: "Service Now",
    cardMatch: "Approval",
    cardTaskTitle: "2 Requests",
    //cardColor: "rgba(255, 70, 117, 1)",
    cardColor: "#fff",
  },
  {
    cardId: "1004",
    cardTitle: "Concur",
    cardMatch: "Concur",
    cardTaskTitle: "2 Requests",
    //cardColor: "rgba(51, 51, 51, 1)",
    cardColor: "#fff",
  },
  {
    cardId: "1005",
    cardTitle: "Git",
    cardMatch: "Git",
    cardTaskTitle: "1 Request",
    //cardColor: "rgba(51, 51, 51, 1)",
    cardColor: "#fff",
  },
  {
    cardId: "1006",
    cardTitle: "Jira",
    cardMatch: "Jira",
    cardTaskTitle: "1 Request",
    //cardColor: "rgba(51, 51, 51, 1)",
    cardColor: "#fff",
  },
];

export const chatMessages = [
  {
    assistantMsg1: "Hey Rob! How can I help you?",
    userMsg: "Take me to my Today's Task List",
    assistantMsg2: "Okay! Here you go",
    routeTo: "/mytask",
  },
  {
    assistantMsg1: "Hey Rob! How can I help you?",
    userMsg: "Take me to my Today's Approval List",
    assistantMsg2: "Okay! Here you go",
    routeTo: "/myapprovals",
  },
  {
    assistantMsg1: "Hey Rob! How can I help you?",
    userMsg: "Schedule meeting with Alex, Debbie for Tommorow",
    assistantMsg2: "Okay! Here you go",
    routeTo: "/schedulemeeting",
  },
  {
    assistantMsg1: "Hey Rob! How can I help you?",
    userMsg: "Take me to my Today's Meeting List",
    assistantMsg2: "Okay! Here you go",
    routeTo: "/mymeetings",
  },
];

export const documentList = [
  {
    itemId: "3001",
    itemTitle: "Questionaires",
  },
  {
    itemId: "3002",
    itemTitle: "Presentation",
  },
  {
    itemId: "3003",
    itemTitle: "Assets",
  },
  {
    itemId: "3004",
    itemTitle: "Branding",
  },
  {
    itemId: "3005",
    itemTitle: "Timeline",
  },
  {
    itemId: "3006",
    itemTitle: "Plan",
  },
];

export const taskDetailsDesc =
  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged";

export const itemDetails = [
  {
    cardId: "2001",
    cardTitle: "Innovation Discussion",
    cardTaskTitle: "9:00 am, 9:15 am",
    //cardColor: "#fff",
    cardColor: "#fff",
    cardCategory: "Meetings",
    cardType: "Meetings",
    metricCompletion: "80%",
  },
  {
    cardId: "2003",
    cardTitle: "Resource Report",
    cardTaskTitle: "Medium Priority",
    //cardColor: "#fff",
    cardColor: "#fff",
    cardCategory: "Mail",
    cardType: "Non Approval",
    metricCompletion: "UnRead",
  },
  {
    cardId: "2005",
    cardTitle: "Sprint Report",
    cardTaskTitle: "High Priority",
    //cardColor: "#fff",
    cardColor: "#fff",
    cardCategory: "Mail",
    cardType: "Non Approval",
    metricCompletion: "Read",
  },
  {
    cardId: "2004",
    cardTitle: "AD Change Request, Sofie",
    cardTaskTitle: "High Priority, Requested on 8:00 AM",
    //cardColor: "#fff",
    cardColor: "#fff",
    cardCategory: "Approval",
    cardType: "Approval",
    metricCompletion: "NotApproved",
  },
  {
    cardId: "2091",
    cardTitle: "PR2119 Approval, Erik",
    cardTaskTitle: "High Priority, Requested on 11:30 AM",
    //cardColor: "#fff",
    cardColor: "#fff",
    cardCategory: "Git",
    cardType: "Approval",
    metricCompletion: "NotApproved",
  },
  {
    cardId: "2002",
    cardTitle: "Jira Task SAMPRJ124 assigned",
    cardTaskTitle: "High Priority, Assigned on 11:30 AM",
    //cardColor: "#fff",
    cardColor: "#fff",
    cardCategory: "Jira",
    cardType: "Approval",
    metricCompletion: "70%",
  },
  {
    cardId: "2051",
    cardTitle: "Concur Approval, Rakesh",
    cardTaskTitle: "High Priority, Requested on 9:12 am",
    //cardColor: "#fff",
    cardColor: "#fff",
    cardCategory: "Concur",
    cardType: "Approval",
    metricCompletion: "NotApproved",
  },
  {
    cardId: "2006",
    cardTitle: "Daily Scrum Call",
    cardTaskTitle: "9:00 am, 9:15 am",
    //cardColor: "#fff",
    cardColor: "#fff",
    cardCategory: "Meetings",
    cardType: "Meetings",
    metricCompletion: "40%",
  },
  {
    cardId: "2007",
    cardTitle: "Leader's TownHall",
    cardTaskTitle: "10:00 AM, 11:00 AM",
    //cardColor: "#fff",
    cardColor: "#fff",
    cardCategory: "Meetings",
    cardType: "Meetings",
    metricCompletion: "90%",
  },
  {
    cardId: "2008",
    cardTitle: "MOM, Transition Meeting",
    cardTaskTitle: "Medium Priority",
    //cardColor: "#fff",
    cardColor: "#fff",
    cardCategory: "Mail",
    cardType: "Non Approval",
    metricCompletion: "Read",
  },
  {
    cardId: "2009",
    cardTitle: "AD Delete Request, Debbie",
    cardTaskTitle: "High Priority, Approved on 26 Jul",
    cardColor: "#fff",
    cardCategory: "Approval",
    cardType: "Approval",
    metricCompletion: "Approved",
  },
  {
    cardId: "2010",
    cardTitle: "Concur Approval, Alan",
    cardTaskTitle: "Medium Priority, Requested on 24 Jul",
    cardColor: "#fff",
    cardCategory: "Concur",
    cardType: "Approval",
    metricCompletion: "Approved",
  },
  {
    cardId: "2011",
    cardTitle: "Daily Scrum Call",
    cardTaskTitle: "9:00 AM, 9:15 AM",
    cardColor: "#fff",
    cardCategory: "Meetings",
    cardType: "Meetings",
    metricCompletion: "50%",
  },
  {
    cardId: "2012",
    cardTitle: "Leader's TownHall",
    cardTaskTitle: "10:00 AM, 11:00 AM",
    cardColor: "#fff",
    cardCategory: "Meetings",
    cardType: "Meetings",
    metricCompletion: "50%",
  },
  {
    cardId: "2013",
    cardTitle: "Resource Utiization Report",
    cardTaskTitle: "Medium Priority",
    cardColor: "#fff",
    cardCategory: "Mail",
    cardType: "Non Approval",
    metricCompletion: "Read",
  },
];

// export const itemDetails = [
//   {
//     cardId: "2001",
//     cardTitle: "Innovation Discussion",
//     cardTaskTitle: "9:00 am, 9:15 am",
//     cardColor: "rgb(255, 192, 56)",
//     cardCategory: "Meetings",
//     metricCompletion: "80%",
//   },
//   {
//     cardId: "2003",
//     cardTitle: "Resource Report",
//     cardTaskTitle: "Medium Priority",
//     cardColor: "rgb(11, 165, 254)",
//     cardCategory: "Mail",
//     metricCompletion: "UnRead",
//   },
//   {
//     cardId: "2005",
//     cardTitle: "Sprint Report",
//     cardTaskTitle: "High Priority",
//     cardColor: "rgb(11, 165, 254)",
//     cardCategory: "Mail",
//     metricCompletion: "Read",
//   },
//   {
//     cardId: "2004",
//     cardTitle: "AD Change Request, Sofie",
//     cardTaskTitle: "High Priority, Requested on 8:00 AM",
//     cardColor: "rgb(255, 70, 117)",
//     cardCategory: "Approval",
//     metricCompletion: "NotApproved",
//   },
//   {
//     cardId: "2091",
//     cardTitle: "AD Change Request, Tom",
//     cardTaskTitle: "High Priority, Requested on 8:30 AM",
//     cardColor: "rgb(255, 70, 117)",
//     cardCategory: "Approval",
//     metricCompletion: "NotApproved",
//   },
//   {
//     cardId: "2002",
//     cardTitle: "Leader's TownHall",
//     cardTaskTitle: "10:00 am, 11:00 am",
//     cardColor: "rgb(255, 192, 56)",
//     cardCategory: "Meetings",
//     metricCompletion: "70%",
//   },
//   {
//     cardId: "2051",
//     cardTitle: "Concur Approval, Rakesh",
//     cardTaskTitle: "High Priority, Requested on 9:12 am",
//     cardColor: "rgb(51, 51, 51)",
//     cardCategory: "Approval",
//     metricCompletion: "NotApproved",
//   },
//   {
//     cardId: "2006",
//     cardTitle: "Daily Scrum Call",
//     cardTaskTitle: "9:00 am, 9:15 am",
//     cardColor: "rgb(255, 192, 56)",
//     cardCategory: "Meetings",
//     metricCompletion: "40%",
//   },
//   {
//     cardId: "2007",
//     cardTitle: "Leader's TownHall",
//     cardTaskTitle: "10:00 AM, 11:00 AM",
//     cardColor: "rgb(255, 192, 56)",
//     cardCategory: "Meetings",
//     metricCompletion: "90%",
//   },
//   {
//     cardId: "2008",
//     cardTitle: "MOM, Transition Meeting",
//     cardTaskTitle: "Medium Priority",
//     cardColor: "rgb(11, 165, 254)",
//     cardCategory: "Mail",
//     metricCompletion: "Read",
//   },
//   {
//     cardId: "2009",
//     cardTitle: "AD Delete Request, Debbie",
//     cardTaskTitle: "High Priority, Approved on 26 Jul",
//     cardColor: "rgb(255, 70, 117)",
//     cardCategory: "Approval",
//     metricCompletion: "Approved",
//   },
//   {
//     cardId: "2010",
//     cardTitle: "Concur Approval, Alan",
//     cardTaskTitle: "Medium Priority, Requested on 24 Jul",
//     cardColor: "rgb(51, 51, 51)",
//     cardCategory: "Approval",
//     metricCompletion: "Approved",
//   },
//   {
//     cardId: "2011",
//     cardTitle: "Daily Scrum Call",
//     cardTaskTitle: "9:00 AM, 9:15 AM",
//     cardColor: "rgb(255, 192, 56)",
//     cardCategory: "Meetings",
//     metricCompletion: "50%",
//   },
//   {
//     cardId: "2012",
//     cardTitle: "Leader's TownHall",
//     cardTaskTitle: "10:00 AM, 11:00 AM",
//     cardColor: "rgb(255, 192, 56)",
//     cardCategory: "Meetings",
//     metricCompletion: "50%",
//   },
//   {
//     cardId: "2013",
//     cardTitle: "Resource Utiization Report",
//     cardTaskTitle: "Medium Priority",
//     cardColor: "rgb(11, 165, 254)",
//     cardCategory: "Mail",
//     metricCompletion: "Read",
//   },
//   {
//     cardId: "2014",
//     cardTitle: "AD Group Change, Sofie",
//     cardTaskTitle: "Medium Priority, Requested on Jul 23",
//     cardColor: "rgb(255, 70, 117)",
//     cardCategory: "Approval",
//     metricCompletion: "NotApproved",
//   },
//   {
//     cardId: "2015",
//     cardTitle: "Concur Approval, Sofie",
//     cardTaskTitle: "Medium Priority, Requested on 10:00 AM",
//     cardColor: "rgb(51, 51, 51)",
//     cardCategory: "Approval",
//     metricCompletion: "Approved",
//   },
//   {
//     cardId: "2016",
//     cardTitle: "Daily Scrum Call",
//     cardTaskTitle: "9:00 AM, 9:15 AM",
//     cardColor: "rgb(255, 192, 56)",
//     cardCategory: "Meetings",
//     metricCompletion: "50%",
//   },
//   {
//     cardId: "2017",
//     cardTitle: "Leader's TownHall",
//     cardTaskTitle: "10:00 AM, 11:00 AM",
//     cardColor: "rgb(255, 192, 56)",
//     cardCategory: "Meetings",
//     metricCompletion: "50%",
//   },
//   {
//     cardId: "2018",
//     cardTitle: "Resource Utiization Report",
//     cardTaskTitle: "Medium Priority",
//     cardColor: "rgb(11, 165, 254)",
//     cardCategory: "Mail",
//     metricCompletion: "Read",
//   },
//   {
//     cardId: "2019",
//     cardTitle: "AD Group Change, Sofie",
//     cardTaskTitle: "Delay by 1 day",
//     cardColor: "rgb(255, 70, 117)",
//     cardCategory: "Approval",
//     metricCompletion: "NotApproved",
//   },
//   {
//     cardId: "2020",
//     cardTitle: "Concur Approval, Sofie",
//     cardTaskTitle: "Requested on 8:00 AM",
//     cardColor: "rgb(51, 51, 51)",
//     cardCategory: "Approval",
//     metricCompletion: "Approved",
//   },
//   {
//     cardId: "2021",
//     cardTitle: "Daily Scrum Call",
//     cardTaskTitle: "9:00 AM, 9:15 AM",
//     cardColor: "rgb(255, 192, 56)",
//     cardCategory: "Meetings",
//     metricCompletion: "50%",
//   },
//   {
//     cardId: "2022",
//     cardTitle: "Leader's TownHall",
//     cardTaskTitle: "10:00 AM, 11:00 AM",
//     cardColor: "rgb(255, 192, 56)",
//     cardCategory: "Meetings",
//     metricCompletion: "50%",
//   },
//   {
//     cardId: "2023",
//     cardTitle: "Resource Utiization Report",
//     cardTaskTitle: "Medium Priority",
//     cardColor: "rgb(11, 165, 254)",
//     cardCategory: "Mail",
//     metricCompletion: "Read",
//   },
//   {
//     cardId: "2024",
//     cardTitle: "AD Group Change, Sofie",
//     cardTaskTitle: "Delay by 1 day",
//     cardColor: "rgb(255, 70, 117)",
//     cardCategory: "Approval",
//     metricCompletion: "NotApproved",
//   },
//   {
//     cardId: "2025",
//     cardTitle: "Concur Approval, Sofie",
//     cardTaskTitle: "Requested on 8:00 AM",
//     cardColor: "rgb(51, 51, 51)",
//     cardCategory: "Approval",
//     metricCompletion: "Approved",
//   },
//   {
//     cardId: "2026",
//     cardTitle: "Daily Scrum Call",
//     cardTaskTitle: "9:00 AM, 9:15 AM",
//     cardColor: "rgb(255, 192, 56)",
//     cardCategory: "Meetings",
//     metricCompletion: "50%",
//   },
//   {
//     cardId: "2027",
//     cardTitle: "Leader's TownHall",
//     cardTaskTitle: "10:00 AM, 11:00 AM",
//     cardColor: "rgb(255, 192, 56)",
//     cardCategory: "Meetings",
//     metricCompletion: "50%",
//   },
//   {
//     cardId: "2028",
//     cardTitle: "Resource Utiization Report",
//     cardTaskTitle: "Medium Priority",
//     cardColor: "rgb(11, 165, 254)",
//     cardCategory: "Mail",
//     metricCompletion: "Read",
//   },
//   {
//     cardId: "2029",
//     cardTitle: "AD Group Change, Sofie",
//     cardTaskTitle: "Delay by 1 day",
//     cardColor: "rgb(255, 70, 117)",
//     cardCategory: "Approval",
//     metricCompletion: "NotApproved",
//   },
//   {
//     cardId: "2030",
//     cardTitle: "Concur Approval, Sofie",
//     cardTaskTitle: "Requested on 8:00 AM",
//     cardColor: "rgb(51, 51, 51)",
//     cardCategory: "Approval",
//     metricCompletion: "Approved",
//   },
//   {
//     cardId: "2031",
//     cardTitle: "Daily Scrum Call",
//     cardTaskTitle: "9:00 AM, 9:15 AM",
//     cardColor: "rgb(255, 192, 56)",
//     cardCategory: "Meetings",
//     metricCompletion: "50%",
//   },
//   {
//     cardId: "2032",
//     cardTitle: "Leader's TownHall",
//     cardTaskTitle: "10:00 AM, 11:00 AM",
//     cardColor: "rgb(255, 192, 56)",
//     cardCategory: "Meetings",
//     metricCompletion: "50%",
//   },
//   {
//     cardId: "2033",
//     cardTitle: "Resource Utiization Report",
//     cardTaskTitle: "Medium Priority",
//     cardColor: "rgb(11, 165, 254)",
//     cardCategory: "Mail",
//     metricCompletion: "Read",
//   },
//   {
//     cardId: "2034",
//     cardTitle: "AD Group Change, Sofie",
//     cardTaskTitle: "Delay by 1 day",
//     cardColor: "rgb(255, 70, 117)",
//     cardCategory: "Approval",
//     metricCompletion: "NotApproved",
//   },
//   {
//     cardId: "2035",
//     cardTitle: "Concur Approval, Sofie",
//     cardTaskTitle: "Requested on 8:00 AM",
//     cardColor: "rgb(51, 51, 51)",
//     cardCategory: "Approval",
//     metricCompletion: "Approved",
//   },
//   {
//     cardId: "2036",
//     cardTitle: "Daily Scrum Call",
//     cardTaskTitle: "9:00 AM, 9:15 AM",
//     cardColor: "rgb(255, 192, 56)",
//     cardCategory: "Meetings",
//     metricCompletion: "50%",
//   },
//   {
//     cardId: "2037",
//     cardTitle: "Leader's TownHall",
//     cardTaskTitle: "10:00 AM, 11:00 AM",
//     cardColor: "rgb(255, 192, 56)",
//     cardCategory: "Meetings",
//     metricCompletion: "50%",
//   },
//   {
//     cardId: "2038",
//     cardTitle: "Resource Utiization Report",
//     cardTaskTitle: "Medium Priority",
//     cardColor: "rgb(11, 165, 254)",
//     cardCategory: "Mail",
//     metricCompletion: "Read",
//   },
//   {
//     cardId: "2039",
//     cardTitle: "AD Group Change, Sofie",
//     cardTaskTitle: "Delay by 1 day",
//     cardColor: "rgb(255, 70, 117)",
//     cardCategory: "Approval",
//     metricCompletion: "NotApproved",
//   },
//   {
//     cardId: "2040",
//     cardTitle: "Concur Approval, Sofie",
//     cardTaskTitle: "Requested on 8:00 AM",
//     cardColor: "rgb(51, 51, 51)",
//     cardCategory: "Approval",
//     metricCompletion: "Approved",
//   },
//   {
//     cardId: "2041",
//     cardTitle: "Daily Scrum Call",
//     cardTaskTitle: "9:00 AM, 9:15 AM",
//     cardColor: "rgb(255, 192, 56)",
//     cardCategory: "Meetings",
//     metricCompletion: "50%",
//   },
//   {
//     cardId: "2042",
//     cardTitle: "Leader's TownHall",
//     cardTaskTitle: "10:00 AM, 11:00 AM",
//     cardColor: "rgb(255, 192, 56)",
//     cardCategory: "Meetings",
//     metricCompletion: "50%",
//   },
//   {
//     cardId: "2043",
//     cardTitle: "Resource Utiization Report",
//     cardTaskTitle: "Medium Priority",
//     cardColor: "rgb(11, 165, 254)",
//     cardCategory: "Mail",
//     metricCompletion: "Read",
//   },
//   {
//     cardId: "2044",
//     cardTitle: "AD Group Change, Sofie",
//     cardTaskTitle: "Delay by 1 day",
//     cardColor: "rgb(255, 70, 117)",
//     cardCategory: "Approval",
//     metricCompletion: "NotApproved",
//   },
//   {
//     cardId: "2045",
//     cardTitle: "Concur Approval, Sofie",
//     cardTaskTitle: "Requested on 8:00 AM",
//     cardColor: "rgb(51, 51, 51)",
//     cardCategory: "Approval",
//     metricCompletion: "Approved",
//   },
//   {
//     cardId: "2046",
//     cardTitle: "Daily Scrum Call",
//     cardTaskTitle: "9:00 AM, 9:15 AM",
//     cardColor: "rgb(255, 192, 56)",
//     cardCategory: "Meetings",
//     metricCompletion: "50%",
//   },
//   {
//     cardId: "2047",
//     cardTitle: "Leader's TownHall",
//     cardTaskTitle: "10:00 AM, 11:00 AM",
//     cardColor: "rgb(255, 192, 56)",
//     cardCategory: "Meetings",
//     metricCompletion: "50%",
//   },
// ];
