export const categoryCardDetails = [
  {
    cardId: "1001",
    cardTitle: "Meetings",
    cardTaskTitle: "8 Requests",
    cardColor: "rgba(255, 192, 56, 1)",
  },
  {
    cardId: "1002",
    cardTitle: "Mails",
    cardTaskTitle: "12 Unread",
    cardColor: "rgba(11, 165, 254, 1)",
  },
  {
    cardId: "1003",
    cardTitle: "Approvals",
    cardTaskTitle: "19 Requests",
    cardColor: "rgba(255, 70, 117, 1)",
  },
  {
    cardId: "1004",
    cardTitle: "Concur",
    cardTaskTitle: "8 Requests",
    cardColor: "rgba(51, 51, 51, 1)",
  },
];

export const itemDetails = [
  {
    cardId: "2001",
    cardTitle: "Daily Scrum Call",
    cardTaskTitle: "9:00 AM - 9:15 AM",
    cardColor: "rgb(255, 192, 56)",
    cardCategory: "Meetings",
    metricCompletion: "80%",
  },
  {
    cardId: "2003",
    cardTitle: "Resource Report",
    cardTaskTitle: "Medium Priority",
    cardColor: "rgb(11, 165, 254)",
    cardCategory: "Mail",
    metricCompletion: "UnRead",
  },
  {
    cardId: "2005",
    cardTitle: "Sprint Report",
    cardTaskTitle: "High Priority",
    cardColor: "rgb(11, 165, 254)",
    cardCategory: "Mail",
    metricCompletion: "Read",
  },
  {
    cardId: "2004",
    cardTitle: "AD Change Request - Sofie",
    cardTaskTitle: "Approved",
    cardColor: "rgb(255, 70, 117)",
    cardCategory: "Approval",
    metricCompletion: "Approved",
  },
  {
    cardId: "2004",
    cardTitle: "AD Change Request - Tom",
    cardTaskTitle: "Delay by 1 day",
    cardColor: "rgb(255, 70, 117)",
    cardCategory: "Approval",
    metricCompletion: "NotApproved",
  },
  {
    cardId: "2002",
    cardTitle: "Leader's TownHall",
    cardTaskTitle: "10:00 AM - 11:00 AM",
    cardColor: "rgb(255, 192, 56)",
    cardCategory: "Meetings",
    metricCompletion: "70%",
  },
  {
    cardId: "2005",
    cardTitle: "Concur Approval - Rakesh",
    cardTaskTitle: "Requested on 8:00 AM",
    cardColor: "rgb(51, 51, 51)",
    cardCategory: "Concur",
    metricCompletion: "Approved",
  },
  {
    cardId: "2006",
    cardTitle: "Daily Scrum Call",
    cardTaskTitle: "9:00 AM - 9:15 AM",
    cardColor: "rgb(255, 192, 56)",
    cardCategory: "Meetings",
    metricCompletion: "40%",
  },
  {
    cardId: "2007",
    cardTitle: "Leader's TownHall",
    cardTaskTitle: "10:00 AM - 11:00 AM",
    cardColor: "rgb(255, 192, 56)",
    cardCategory: "Meetings",
    metricCompletion: "90%",
  },
  {
    cardId: "2008",
    cardTitle: "MOM - Transition Meeting",
    cardTaskTitle: "Medium Priority",
    cardColor: "rgb(11, 165, 254)",
    cardCategory: "Mail",
    metricCompletion: "Read",
  },
  {
    cardId: "2009",
    cardTitle: "AD Delete Request - Debbie",
    cardTaskTitle: "Delay by 1 day",
    cardColor: "rgb(255, 70, 117)",
    cardCategory: "Approval",
    metricCompletion: "NotApproved",
  },
  {
    cardId: "2010",
    cardTitle: "Concur Approval - Alan",
    cardTaskTitle: "Requested on 8:00 AM",
    cardColor: "rgb(51, 51, 51)",
    cardCategory: "Concur",
    metricCompletion: "Approved",
  },
  {
    cardId: "2011",
    cardTitle: "Daily Scrum Call",
    cardTaskTitle: "9:00 AM - 9:15 AM",
    cardColor: "rgb(255, 192, 56)",
    cardCategory: "Meetings",
    metricCompletion: "50%",
  },
  {
    cardId: "2012",
    cardTitle: "Leader's TownHall",
    cardTaskTitle: "10:00 AM - 11:00 AM",
    cardColor: "rgb(255, 192, 56)",
    cardCategory: "Meetings",
    metricCompletion: "50%",
  },
  {
    cardId: "2013",
    cardTitle: "Resource Utiization Report",
    cardTaskTitle: "Medium Priority",
    cardColor: "rgb(11, 165, 254)",
    cardCategory: "Mail",
    metricCompletion: "Read",
  },
  {
    cardId: "2014",
    cardTitle: "AD Group Member Change Request - Sofie",
    cardTaskTitle: "Delay by 1 day",
    cardColor: "rgb(255, 70, 117)",
    cardCategory: "Approval",
    metricCompletion: "NotApproved",
  },
  {
    cardId: "2015",
    cardTitle: "Concur Prioritization Approval - Sofie",
    cardTaskTitle: "Requested on 8:00 AM",
    cardColor: "rgb(51, 51, 51)",
    cardCategory: "Concur",
    metricCompletion: "Approved",
  },
  {
    cardId: "2016",
    cardTitle: "Daily Scrum Call",
    cardTaskTitle: "9:00 AM - 9:15 AM",
    cardColor: "rgb(255, 192, 56)",
    cardCategory: "Meetings",
    metricCompletion: "50%",
  },
  {
    cardId: "2017",
    cardTitle: "Leader's TownHall",
    cardTaskTitle: "10:00 AM - 11:00 AM",
    cardColor: "rgb(255, 192, 56)",
    cardCategory: "Meetings",
    metricCompletion: "50%",
  },
  {
    cardId: "2018",
    cardTitle: "Resource Utiization Report",
    cardTaskTitle: "Medium Priority",
    cardColor: "rgb(11, 165, 254)",
    cardCategory: "Mail",
    metricCompletion: "Read",
  },
  {
    cardId: "2019",
    cardTitle: "AD Group Member Change Request - Sofie",
    cardTaskTitle: "Delay by 1 day",
    cardColor: "rgb(255, 70, 117)",
    cardCategory: "Approval",
    metricCompletion: "NotApproved",
  },
  {
    cardId: "2020",
    cardTitle: "Concur Prioritization Approval - Sofie",
    cardTaskTitle: "Requested on 8:00 AM",
    cardColor: "rgb(51, 51, 51)",
    cardCategory: "Concur",
    metricCompletion: "Approved",
  },
  {
    cardId: "2021",
    cardTitle: "Daily Scrum Call",
    cardTaskTitle: "9:00 AM - 9:15 AM",
    cardColor: "rgb(255, 192, 56)",
    cardCategory: "Meetings",
    metricCompletion: "50%",
  },
  {
    cardId: "2022",
    cardTitle: "Leader's TownHall",
    cardTaskTitle: "10:00 AM - 11:00 AM",
    cardColor: "rgb(255, 192, 56)",
    cardCategory: "Meetings",
    metricCompletion: "50%",
  },
  {
    cardId: "2023",
    cardTitle: "Resource Utiization Report",
    cardTaskTitle: "Medium Priority",
    cardColor: "rgb(11, 165, 254)",
    cardCategory: "Mail",
    metricCompletion: "Read",
  },
  {
    cardId: "2024",
    cardTitle: "AD Group Member Change Request - Sofie",
    cardTaskTitle: "Delay by 1 day",
    cardColor: "rgb(255, 70, 117)",
    cardCategory: "Approval",
    metricCompletion: "NotApproved",
  },
  {
    cardId: "2025",
    cardTitle: "Concur Prioritization Approval - Sofie",
    cardTaskTitle: "Requested on 8:00 AM",
    cardColor: "rgb(51, 51, 51)",
    cardCategory: "Concur",
    metricCompletion: "Approved",
  },
  {
    cardId: "2026",
    cardTitle: "Daily Scrum Call",
    cardTaskTitle: "9:00 AM - 9:15 AM",
    cardColor: "rgb(255, 192, 56)",
    cardCategory: "Meetings",
    metricCompletion: "50%",
  },
  {
    cardId: "2027",
    cardTitle: "Leader's TownHall",
    cardTaskTitle: "10:00 AM - 11:00 AM",
    cardColor: "rgb(255, 192, 56)",
    cardCategory: "Meetings",
    metricCompletion: "50%",
  },
  {
    cardId: "2028",
    cardTitle: "Resource Utiization Report",
    cardTaskTitle: "Medium Priority",
    cardColor: "rgb(11, 165, 254)",
    cardCategory: "Mail",
    metricCompletion: "Read",
  },
  {
    cardId: "2029",
    cardTitle: "AD Group Member Change Request - Sofie",
    cardTaskTitle: "Delay by 1 day",
    cardColor: "rgb(255, 70, 117)",
    cardCategory: "Approval",
    metricCompletion: "NotApproved",
  },
  {
    cardId: "2030",
    cardTitle: "Concur Prioritization Approval - Sofie",
    cardTaskTitle: "Requested on 8:00 AM",
    cardColor: "rgb(51, 51, 51)",
    cardCategory: "Concur",
    metricCompletion: "Approved",
  },
  {
    cardId: "2031",
    cardTitle: "Daily Scrum Call",
    cardTaskTitle: "9:00 AM - 9:15 AM",
    cardColor: "rgb(255, 192, 56)",
    cardCategory: "Meetings",
    metricCompletion: "50%",
  },
  {
    cardId: "2032",
    cardTitle: "Leader's TownHall",
    cardTaskTitle: "10:00 AM - 11:00 AM",
    cardColor: "rgb(255, 192, 56)",
    cardCategory: "Meetings",
    metricCompletion: "50%",
  },
  {
    cardId: "2033",
    cardTitle: "Resource Utiization Report",
    cardTaskTitle: "Medium Priority",
    cardColor: "rgb(11, 165, 254)",
    cardCategory: "Mail",
    metricCompletion: "Read",
  },
  {
    cardId: "2034",
    cardTitle: "AD Group Member Change Request - Sofie",
    cardTaskTitle: "Delay by 1 day",
    cardColor: "rgb(255, 70, 117)",
    cardCategory: "Approval",
    metricCompletion: "NotApproved",
  },
  {
    cardId: "2035",
    cardTitle: "Concur Prioritization Approval - Sofie",
    cardTaskTitle: "Requested on 8:00 AM",
    cardColor: "rgb(51, 51, 51)",
    cardCategory: "Concur",
    metricCompletion: "Approved",
  },
  {
    cardId: "2036",
    cardTitle: "Daily Scrum Call",
    cardTaskTitle: "9:00 AM - 9:15 AM",
    cardColor: "rgb(255, 192, 56)",
    cardCategory: "Meetings",
    metricCompletion: "50%",
  },
  {
    cardId: "2037",
    cardTitle: "Leader's TownHall",
    cardTaskTitle: "10:00 AM - 11:00 AM",
    cardColor: "rgb(255, 192, 56)",
    cardCategory: "Meetings",
    metricCompletion: "50%",
  },
  {
    cardId: "2038",
    cardTitle: "Resource Utiization Report",
    cardTaskTitle: "Medium Priority",
    cardColor: "rgb(11, 165, 254)",
    cardCategory: "Mail",
    metricCompletion: "Read",
  },
  {
    cardId: "2039",
    cardTitle: "AD Group Member Change Request - Sofie",
    cardTaskTitle: "Delay by 1 day",
    cardColor: "rgb(255, 70, 117)",
    cardCategory: "Approval",
    metricCompletion: "NotApproved",
  },
  {
    cardId: "2040",
    cardTitle: "Concur Prioritization Approval - Sofie",
    cardTaskTitle: "Requested on 8:00 AM",
    cardColor: "rgb(51, 51, 51)",
    cardCategory: "Concur",
    metricCompletion: "Approved",
  },
  {
    cardId: "2041",
    cardTitle: "Daily Scrum Call",
    cardTaskTitle: "9:00 AM - 9:15 AM",
    cardColor: "rgb(255, 192, 56)",
    cardCategory: "Meetings",
    metricCompletion: "50%",
  },
  {
    cardId: "2042",
    cardTitle: "Leader's TownHall",
    cardTaskTitle: "10:00 AM - 11:00 AM",
    cardColor: "rgb(255, 192, 56)",
    cardCategory: "Meetings",
    metricCompletion: "50%",
  },
  {
    cardId: "2043",
    cardTitle: "Resource Utiization Report",
    cardTaskTitle: "Medium Priority",
    cardColor: "rgb(11, 165, 254)",
    cardCategory: "Mail",
    metricCompletion: "Read",
  },
  {
    cardId: "2044",
    cardTitle: "AD Group Member Change Request - Sofie",
    cardTaskTitle: "Delay by 1 day",
    cardColor: "rgb(255, 70, 117)",
    cardCategory: "Approval",
    metricCompletion: "NotApproved",
  },
  {
    cardId: "2045",
    cardTitle: "Concur Prioritization Approval - Sofie",
    cardTaskTitle: "Requested on 8:00 AM",
    cardColor: "rgb(51, 51, 51)",
    cardCategory: "Concur",
    metricCompletion: "Approved",
  },
  {
    cardId: "2046",
    cardTitle: "Daily Scrum Call",
    cardTaskTitle: "9:00 AM - 9:15 AM",
    cardColor: "rgb(255, 192, 56)",
    cardCategory: "Meetings",
    metricCompletion: "50%",
  },
  {
    cardId: "2047",
    cardTitle: "Leader's TownHall",
    cardTaskTitle: "10:00 AM - 11:00 AM",
    cardColor: "rgb(255, 192, 56)",
    cardCategory: "Meetings",
    metricCompletion: "50%",
  },
];
